#!/usr/bin/env python
# https://rg3.name/200711221740.html
import mailbox
import os.path
import re
import sys

try:
    appname = os.path.basename(sys.argv[0])
    source = sys.argv[1]
    dest = sys.argv[2]

    (sfmt, dfmt) = re.match(r'^(.+)2(.+)', appname).groups()
    sbox = mailbox.__dict__[sfmt](source)
    dbox = mailbox.__dict__[dfmt](dest)

    for key in sbox.iterkeys():
        dbox.add(sbox.get_message(key))

except IndexError:
    sys.exit('Usage: %s SOURCE DESTINATION' % appname)
except (AttributeError, KeyError):
    sys.exit('ERROR: invalid mailbox type')
except mailbox.Error, err:
    sys.exit('ERROR: %s' % err)
